version: "3.7"
services:
  traefik:
    image: traefik:v2.1.1
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "8080:8080"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--log.filePath=/var/log/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--accesslog.bufferingsize=100"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.samplingServerURL=http://localhost:5778/sampling"
      - "--tracing.jaeger.samplingType=const"
      - "--tracing.jaeger.samplingParam=1.0"
      - "--tracing.jaeger.localAgentHostPort=127.0.0.1:6831"
      - "--tracing.jaeger.propagation=jaeger"
      - "--tracing.jaeger.traceContextHeaderName=uber-trace-id"
      - "--metrics.prometheus=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - traefik-logs:/var/log/traefik

  jaeger:
    image: jaegertracing/all-in-one:1.16
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 
    restart: unless-stopped
    ports:  
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    labels:
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.local`)"
      - "traefik.port=16686"

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ~/srv/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  traefik-logs:

